name: "Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  node-version: 18.x

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    name: 'MarkdownLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Validate Markdown Sources
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
  eslint:
    runs-on: ubuntu-latest
    name: 'ESLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Validate JS Sources
        run: npm run validate:js
  stylelint:
    runs-on: ubuntu-latest
    name: 'Stylelint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Validate CSS Sources
        run: npm run validate:css
  css-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Compile CSS
        run: npm run compile:css
      - name: Compare
        run: git diff --exit-code
  package-lock-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm install --ignore-scripts
      - name: Compare
        run: git diff --exit-code
