name: "Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  node-version: 18.x

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    name: 'MarkdownLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Validate Markdown Sources
        uses: nosborn/github-action-markdown-cli@9fc95163471d6460c35cccad13645912aaa25d5f # v1.1.1
        with:
          files: .
  eslint:
    runs-on: ubuntu-latest
    name: 'ESLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Validate JS Sources
        run: npm run validate:js
  stylelint:
    runs-on: ubuntu-latest
    name: 'Stylelint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Validate CSS Sources
        run: npm run validate:css
  package-lock-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - run: npm install --ignore-scripts
      - run: git diff --exit-code
